services:
  web:
    container_name: Vjenčanje
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - wedding

    ports:
      - 8080:8080
  db:
    image: sqlite:17





networks:
  wedding: { }
